---
title: "A  study  of  association  between  genetic markers in  candidate  genes  and  production  traits  in  Thai  native chickens "
author: "Jigme Tenzin"
date: '2019'
slug: candidate-genes
categories:
  - Research
tags:
  - candidate genes
  - production traits
  - PCR-RFLP
  - STAT5B
  - DRD2
  - MTNR1C
  - Marker-assisted selection
doi: ''
publishDate: '2019-06-15'
publication: 'Khon Kaen University'
summary: 'Study describing the association of candidate genes and production traits.'
subtitle: 'Candidate genes and production traits in Thai Native chickens'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://opac.kku.ac.th/Catalog/BibItem.aspx?BibID=b00423551
---

<style type="text/css">
.page-main img {
  box-shadow: 0px 0px 2px 2px rgba( 0, 0, 0, 0.2 );
  #/* ease | ease-in | ease-out | linear */
  transition: transform ease-in-out 1s;
}

.page-main img:hover {
  transform: scale(1.8);
}
</style>


## Abstract 

Thai Pradu Hang Dam and Chee chickens are important breeds for sustainable utilization of native breeds. They are adapted to local harsh environmental condition. However, their production performance is low. Therefore, molecular-based selection helps in increasing the selection response and decreasing the generation interval. In this study, we aimed to investigate the association among signal transducers and activator of transcription (STAT5B), dopamine receptors D2 (DRD2), bone morphogenetic protein (BMP15), melatonin receptors type C (MTNR1C) and phenotype and estimated breeding values for growth and reproductive traits in Thai Pradu Hang Dam and Chee chickens. A total of 93 and 95 chicken blood samples of Pradu Hang Dam and Chee respectively were collected and genotyped using polymerase chain reaction-restriction fragment length polymorphism to study the association between candidate genes and estimated breeding value of production traits by GLM procedure. Estimated breeding values were calculated using best linear unbiased prediction (BLUP). In Pradu Hang Dam, a significant association was found among DRD2 polymorphism and estimated breeding values of egg weight at the age at first egg. TC and TT genotype, had higher breeding values than CC genotype. BMP15 with estimated breeding values eight weight at 300 days and body weight at 300 days. TT genotype had higher estimated breeding values for both egg weight and body weight. MTNR1C was found to be associated with estimated breeding values of egg weight at 300 days. Moreover, in Pradu Hang Dam, MTNR1C had significant association of it with egg number at 300 days. Allele A had more egg than allele G. In Chee chickens, MTNR1C was found to be associated with estimated breeding values of egg number at 300 days. In Thai Pradu Hang Dam, the results suggest that we may use DRD2, BMP15, and MTNR1C for early maturity and growth for a balanced selection. We can also use MTNR1C as a gene marker to improve egg number. Subsequently, in Chee we might use MTNR1C as a genetic marker for improving egg production.