---
title: "Potential genetic markers and their association with production traits in Thai Pradu Hang Dam and Chee native chickens"
author: "Jigme Tenzin, Wuttigrai Boonkum1,
and Vibuntita Chankitisakul1"
date: '2020'
slug: genetic-markters
categories:
  - Research
tags:
  - candidate genes
  - Oradu Hang Dam
  - Production Traits
  - Marker-assisted selection
  
doi: './do:10.14456/kaj.2020.19'
publishDate: '2018-06-12'
publication: 'Khon Kaen University'
summary: 'Association of candidate genes with production traits in Thail Chee and Pradu Hang Dam chickens.'
subtitle: 'Potential genetic markers in Thai native chickens'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ag2.kku.ac.th/kaj/PDF.cfm?filename=19_12.pdf&id=4166&keeptrack=10
---

<style type="text/css">
.page-main img {
  box-shadow: 0px 0px 2px 2px rgba( 0, 0, 0, 0.2 );
  #/* ease | ease-in | ease-out | linear */
  transition: transform ease-in-out 1s;
}

.page-main img:hover {
  transform: scale(1.8);
}
</style>


## Abstract 

Native chickens are increasingly selected for better production and performance as they cannot compete with hybrids and exotic breeds in growth and reproductive traits. Traditionally, phenotypic based selection was used to select animal which took longer to improve the animal and their response to selection was minimal. However, nowadays we can select animals at young age using
genetic markers. But we need more genetic markers for a robust selection. Therefore, in this study, we aimed to find the association among MTNR1C, STAT5B, BMP15, and DRD2 with production traits. A sample size of 188 chickens were used with 95 Chee chickens and 93 Pradu Hang Dam chickens.
Blood samples were collected from wing vein. The DNA was isolated with modified form of guanidine hydrochloride method. It was genotyped using PCR-RFLP. The GLM procedure was used to compare the least square means between different genotype. Chi-square goodness of fit test was used to test the Hardy-Weinberg equilibrium. All the genes deviated significantly from Hardy-Weinberg equilibrium
except DRD2. The MTNR1C was significantly associated with age at first egg (AFE) with a allele giving earlier eggs than G allele in Pradu Hang Dam chickens and subsequent higher egg production. However, we didn’t find any association with other genes and productions traits. Moreover, in Chee, we didn’t establish any tentative association with all the genes studied and the production traits. We recommend that MTNR1C can be a potential marker for improving egg production traits. 